
package com.sforce.soap.enterprise;

import javax.xml.ws.WebFault;


/**
 * This class was generated by FuseSource Services Framework 2.5.0.fuse-7-061
 * 2013-01-23T23:53:39.908+05:30
 * Generated source version: 2.5.0.fuse-7-061
 */

@WebFault(name = "InvalidNewPasswordFault", targetNamespace = "urn:fault.enterprise.soap.sforce.com")
public class InvalidNewPasswordFault extends Exception {
    
    private com.sforce.soap.enterprise.fault.InvalidNewPasswordFault invalidNewPasswordFault;

    public InvalidNewPasswordFault() {
        super();
    }
    
    public InvalidNewPasswordFault(String message) {
        super(message);
    }
    
    public InvalidNewPasswordFault(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidNewPasswordFault(String message, com.sforce.soap.enterprise.fault.InvalidNewPasswordFault invalidNewPasswordFault) {
        super(message);
        this.invalidNewPasswordFault = invalidNewPasswordFault;
    }

    public InvalidNewPasswordFault(String message, com.sforce.soap.enterprise.fault.InvalidNewPasswordFault invalidNewPasswordFault, Throwable cause) {
        super(message, cause);
        this.invalidNewPasswordFault = invalidNewPasswordFault;
    }

    public com.sforce.soap.enterprise.fault.InvalidNewPasswordFault getFaultInfo() {
        return this.invalidNewPasswordFault;
    }
}
