
package com.sforce.soap.enterprise;

import javax.xml.ws.WebFault;


/**
 * This class was generated by FuseSource Services Framework 2.5.0.fuse-7-061
 * 2013-01-23T23:53:39.923+05:30
 * Generated source version: 2.5.0.fuse-7-061
 */

@WebFault(name = "LoginFault", targetNamespace = "urn:fault.enterprise.soap.sforce.com")
public class LoginFault extends Exception {
    
    private com.sforce.soap.enterprise.fault.LoginFault loginFault;

    public LoginFault() {
        super();
    }
    
    public LoginFault(String message) {
        super(message);
    }
    
    public LoginFault(String message, Throwable cause) {
        super(message, cause);
    }

    public LoginFault(String message, com.sforce.soap.enterprise.fault.LoginFault loginFault) {
        super(message);
        this.loginFault = loginFault;
    }

    public LoginFault(String message, com.sforce.soap.enterprise.fault.LoginFault loginFault, Throwable cause) {
        super(message, cause);
        this.loginFault = loginFault;
    }

    public com.sforce.soap.enterprise.fault.LoginFault getFaultInfo() {
        return this.loginFault;
    }
}
