
package com.sforce.soap.enterprise;

import javax.xml.ws.WebFault;


/**
 * This class was generated by FuseSource Services Framework 2.5.0.fuse-7-061
 * 2013-01-23T23:53:39.920+05:30
 * Generated source version: 2.5.0.fuse-7-061
 */

@WebFault(name = "MalformedQueryFault", targetNamespace = "urn:fault.enterprise.soap.sforce.com")
public class MalformedQueryFault extends Exception {
    
    private com.sforce.soap.enterprise.fault.MalformedQueryFault malformedQueryFault;

    public MalformedQueryFault() {
        super();
    }
    
    public MalformedQueryFault(String message) {
        super(message);
    }
    
    public MalformedQueryFault(String message, Throwable cause) {
        super(message, cause);
    }

    public MalformedQueryFault(String message, com.sforce.soap.enterprise.fault.MalformedQueryFault malformedQueryFault) {
        super(message);
        this.malformedQueryFault = malformedQueryFault;
    }

    public MalformedQueryFault(String message, com.sforce.soap.enterprise.fault.MalformedQueryFault malformedQueryFault, Throwable cause) {
        super(message, cause);
        this.malformedQueryFault = malformedQueryFault;
    }

    public com.sforce.soap.enterprise.fault.MalformedQueryFault getFaultInfo() {
        return this.malformedQueryFault;
    }
}
