
package com.sforce.soap.enterprise;

import javax.xml.ws.WebFault;


/**
 * This class was generated by FuseSource Services Framework 2.5.0.fuse-7-061
 * 2013-01-23T23:53:39.910+05:30
 * Generated source version: 2.5.0.fuse-7-061
 */

@WebFault(name = "UnexpectedErrorFault", targetNamespace = "urn:fault.enterprise.soap.sforce.com")
public class UnexpectedErrorFault extends Exception {
    
    private com.sforce.soap.enterprise.fault.UnexpectedErrorFault unexpectedErrorFault;

    public UnexpectedErrorFault() {
        super();
    }
    
    public UnexpectedErrorFault(String message) {
        super(message);
    }
    
    public UnexpectedErrorFault(String message, Throwable cause) {
        super(message, cause);
    }

    public UnexpectedErrorFault(String message, com.sforce.soap.enterprise.fault.UnexpectedErrorFault unexpectedErrorFault) {
        super(message);
        this.unexpectedErrorFault = unexpectedErrorFault;
    }

    public UnexpectedErrorFault(String message, com.sforce.soap.enterprise.fault.UnexpectedErrorFault unexpectedErrorFault, Throwable cause) {
        super(message, cause);
        this.unexpectedErrorFault = unexpectedErrorFault;
    }

    public com.sforce.soap.enterprise.fault.UnexpectedErrorFault getFaultInfo() {
        return this.unexpectedErrorFault;
    }
}
